---- Queries for creating the Declaration Voting tables

---- Table 1). Data sourced from EMA markoffs
SELECT  A.ISSUINGDISTAREACODE,
        B.VOTINGCENTRETYPECODE,
        B.GAZETTEDNAME,
        A.DECLARATIONEXCUSEVOTETYPECODE AS DEC_VOTE_TYPE,
        TO_CHAR(A.voteprocesseddate, 'YYYY-MM-DD') AS VOTEPROCESSDATE,
        COUNT(CASE A.VOTESTATUSCODE WHEN 'Accepted' THEN 1 ELSE NULL END) AS ACCEPTED_MARKOFFS,
        COUNT(CASE A.VOTESTATUSCODE WHEN 'Rejected' THEN 1 ELSE NULL END) AS REJECTED_MARKOFFS
FROM PRD2008.ES_DECEXCUSEVOTE A
LEFT JOIN (SELECT GAZETTEDNAME,
                LOCATIONID,
                VOTINGCENTRETYPECODE,
                ELECTIONEVENTID
FROM PRD2008.ES_LOCATIONS
WHERE VOTINGCENTRETYPECODE <> 'RO') B
  ON A.LOCATIONID = B.LOCATIONID
    AND A.VOTINGCENTRETYPECODE = B.VOTINGCENTRETYPECODE
WHERE A.ELECTIONEVENTID = ('LG1701')
  AND B.ELECTIONEVENTID = ('LG1701')
  AND (A.DECLARATIONEXCUSEVOTETYPECODE = 'NAMAV' OR A.DECLARATIONEXCUSEVOTETYPECODE = 'Enrolment')
GROUP BY A.ISSUINGDISTAREACODE, B.GAZETTEDNAME, B.VOTINGCENTRETYPECODE, A.DECLARATIONEXCUSEVOTETYPECODE, TO_CHAR(A.voteprocesseddate, 'YYYY-MM-DD')
ORDER BY A.ISSUINGDISTAREACODE, B.GAZETTEDNAME;



---- Table 2). Data sourced from polling place AoBP 
SELECT  A.AREACODE,
		C.CONTESTAREACODE,
		CASE
		WHEN C.CONTESTTYPECODE = 'By LGA'
		   THEN 'Councillor'
		WHEN C.CONTESTTYPECODE = 'General LGA'
		   THEN 'Councillor'
		WHEN C.CONTESTTYPECODE = 'By LGA Referendum'
		   THEN 'Referendum'
		WHEN C.CONTESTTYPECODE = 'General LGA Ref'
		   THEN 'Referendum'
		WHEN C.CONTESTTYPECODE = 'By LGA Poll'
		   THEN 'Poll'
		WHEN C.CONTESTTYPECODE = 'General LGA Poll'
		   THEN 'Poll'
		WHEN C.CONTESTTYPECODE = 'By Ward'
		   THEN 'Councillor'
		WHEN C.CONTESTTYPECODE = 'General Ward'
		   THEN 'Councillor'
		WHEN C.CONTESTTYPECODE = 'General Mayoralty'
		   THEN 'Mayor'
		WHEN C.CONTESTTYPECODE = 'By Mayoralty'
		   THEN 'Mayor'
		ELSE C.CONTESTTYPECODE
	  END AS CONTESTTYPECODE,
	  B.GAZETTEDNAME AS VENUE,
	  'Polling Place' AS VENUETYPE,
	  A.ENROL_ENVELOPES,
	  A.NAMAV_ENVELOPES
FROM PRD2008.ES_VOTECOUNTINGPOINT A
JOIN (SELECT  GAZETTEDNAME,
			  VOTINGCENTRETYPECODE,
			  LOCATIONID,
			  ELECTIONEVENTID
	  FROM PRD2008.ES_LOCATIONS
	  WHERE VOTINGCENTRETYPECODE = 'PP') B
  ON    A.LOCATIONID = B.LOCATIONID
JOIN PRD2008.ES_CONTEST C
  ON    A.CONTESTID = C.CONTESTID
WHERE A.ELECTIONEVENTID = ('LG1701')
AND B.ELECTIONEVENTID = ('LG1701')
AND C.ELECTIONEVENTID = ('LG1701')
AND C.CONTESTSTATUSTYPECODE = 'Contested'
ORDER BY A.AREACODE, CONTESTTYPECODE, C.CONTESTAREACODE, VENUE;


