SELECT  A.ISSUINGDISTAREACODE,
        B.VOTINGCENTRETYPECODE,
        B.GAZETTEDNAME,
        A.DECLARATIONEXCUSEVOTETYPECODE AS DEC_VOTE_TYPE,
        TO_CHAR(A.voteprocesseddate, 'YYYY-MM-DD') AS VOTEPROCESSDATE,
       COUNT(CASE A.VOTESTATUSCODE WHEN 'Provisional' THEN 1 ELSE NULL END) AS PROVISIONAL_MARKOFFS, 
       COUNT(CASE A.VOTESTATUSCODE WHEN 'Accepted' THEN 1 ELSE NULL END) AS ACCEPTED_MARKOFFS,
       COUNT(CASE A.VOTESTATUSCODE WHEN 'Rejected' THEN 1 ELSE NULL END) AS REJECTED_MARKOFFS
FROM PRD2008.ES_DECEXCUSEVOTE A
LEFT JOIN (SELECT GAZETTEDNAME,
                LOCATIONID,
                VOTINGCENTRETYPECODE,
                ELECTIONEVENTID
FROM PRD2008.ES_LOCATIONS
WHERE VOTINGCENTRETYPECODE <> 'RO') B
  ON A.LOCATIONID = B.LOCATIONID
    AND A.VOTINGCENTRETYPECODE = B.VOTINGCENTRETYPECODE
WHERE A.ELECTIONEVENTID = ('LG2002')
  AND B.ELECTIONEVENTID = ('LG2002')
  AND (A.DECLARATIONEXCUSEVOTETYPECODE = 'NAMAV' OR A.DECLARATIONEXCUSEVOTETYPECODE = 'Enrolment')
GROUP BY A.ISSUINGDISTAREACODE, B.GAZETTEDNAME, B.VOTINGCENTRETYPECODE, A.DECLARATIONEXCUSEVOTETYPECODE, TO_CHAR(A.voteprocesseddate, 'YYYY-MM-DD')
ORDER BY A.ISSUINGDISTAREACODE, B.GAZETTEDNAME;
                                      
                                      


