SELECT  
A.AREACODE,
C.CONTESTAREACODE,
CASE
		WHEN C.CONTESTTYPECODE = 'By LGA'
		   THEN 'Councillor'
		WHEN C.CONTESTTYPECODE = 'General LGA'
		   THEN 'Councillor'
		WHEN C.CONTESTTYPECODE = 'By LGA Referendum'
		   THEN 'Referendum'
		WHEN C.CONTESTTYPECODE = 'General LGA Ref'
		   THEN 'Referendum'
		WHEN C.CONTESTTYPECODE = 'By LGA Poll'
		   THEN 'Poll'
		WHEN C.CONTESTTYPECODE = 'General LGA Poll'
		   THEN 'Poll'
		WHEN C.CONTESTTYPECODE = 'By Ward'
		   THEN 'Councillor'
		WHEN C.CONTESTTYPECODE = 'General Ward'
		   THEN 'Councillor'
		WHEN C.CONTESTTYPECODE = 'General Mayoralty'
		   THEN 'Mayor'
		WHEN C.CONTESTTYPECODE = 'By Mayoralty'
		   THEN 'Mayor'
		ELSE C.CONTESTTYPECODE
	  END AS CONTESTTYPECODE,
	  B.GAZETTEDNAME AS VENUE,
	  B.VOTINGCENTRETYPECODE,
	  A.ENROL_ENVELOPES,
	  A.NAMAV_ENVELOPES
FROM PRD2008.ES_VOTECOUNTINGPOINT A
JOIN (SELECT  GAZETTEDNAME,
			  VOTINGCENTRETYPECODE,
			  LOCATIONID,
			  ELECTIONEVENTID
	  FROM PRD2008.ES_LOCATIONS
	  WHERE VOTINGCENTRETYPECODE != 'RO') B
  ON    A.LOCATIONID = B.LOCATIONID
JOIN PRD2008.ES_CONTEST C
  ON    A.CONTESTID = C.CONTESTID
WHERE A.ELECTIONEVENTID = ('LG1701')
AND B.ELECTIONEVENTID = ('LG1701')
AND C.ELECTIONEVENTID = ('LG1701')
AND C.CONTESTSTATUSTYPECODE = 'Contested'
ORDER BY A.AREACODE, CONTESTTYPECODE, C.CONTESTAREACODE, VENUE;
                                
                                
                                