-- ACCEPTED DEC VOTE MARKOFF COUNTS FROM ES_DECEXCUSEVOTE
SELECT  A.ISSUINGDISTAREACODE,
		B.GAZETTEDNAME,
        TO_CHAR(A.VOTEPROCESSEDDATE, 'YYYY-MM-DD') AS VOTEPROCESSEDDATE,
		COUNT(1) AS PRE_POLL_MARKOFFS


FROM PRD2008.ES_DECEXCUSEVOTE A
LEFT JOIN (SELECT GAZETTEDNAME,
				  LOCATIONID,
				  ELECTIONEVENTID
			FROM PRD2008.ES_LOCATIONS
			WHERE VOTINGCENTRETYPECODE <> 'RO') B
  ON A.LOCATIONID = B.LOCATIONID


--- Getting rid of things
WHERE A.ELECTIONEVENTID = 'LG1701'
  AND B.ELECTIONEVENTID = 'LG1701'
  AND A.DECLARATIONEXCUSEVOTETYPECODE = 'Pre-poll Ordinary'
  AND B.GAZETTEDNAME != 'Sydney Town Hall'


GROUP BY A.ISSUINGDISTAREACODE, B.GAZETTEDNAME, TO_CHAR(A.VOTEPROCESSEDDATE, 'YYYY-MM-DD')
ORDER BY A.ISSUINGDISTAREACODE, B.GAZETTEDNAME ;


